# Generated by Django 2.2.7 on 2019-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='China_Item',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sido', models.CharField(max_length=128)),
                ('sigungu', models.CharField(max_length=128)),
                ('cityGubun', models.CharField(max_length=128)),
                ('marketType', models.CharField(max_length=128)),
                ('userType', models.CharField(max_length=128)),
                ('ageGroup', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=64)),
                ('dtYearMonth', models.CharField(max_length=128)),
                ('userCount', models.IntegerField()),
                ('useCount', models.IntegerField()),
                ('useCost', models.IntegerField()),
            ],
        ),
    ]
