# Generated by Django 2.2.7 on 2019-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='china_item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
