# Generated by Django 2.2.7 on 2019-11-22 13:12

from django.db import migrations

class Migration(migrations.Migration):

	dependencies = [
		('mainapp', '0002_auto_20191122_1307'),
	]

	operations = [
	]
