# Generated by Django 2.2.7 on 2019-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191122_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korea_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sido', models.CharField(max_length=128)),
                ('sigungu', models.CharField(max_length=128)),
                ('cityGubun', models.CharField(max_length=128)),
                ('marketType', models.CharField(max_length=128)),
                ('userType', models.CharField(max_length=128)),
                ('ageGroup', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=64)),
                ('dtYearMonth', models.CharField(max_length=128)),
                ('userCount', models.IntegerField()),
                ('useCount', models.IntegerField()),
                ('useCost', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='china_item',
            name='ageGroup',
        ),
        migrations.RemoveField(
            model_name='china_item',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='china_item',
            name='userType',
        ),
    ]
