# Generated by Django 2.2.7 on 2019-11-22 15:05

from django.db import migrations
import mainapp.utils.Retrieve_Data as RD

def forwards_func(apps, schema_editor):
	# We get the model from the versioned app registry;
	# if we directly import it, it'll be the wrong version





	Items = apps.get_model("mainapp", "China_Item")
	db_alias = schema_editor.connection.alias


	ret = RD.getChineseData("200001","201911",None,None,None,None)

	print (len(ret))

	Item_Lists = []
	for index, row in ret.iterrows():
		print (row)
		Item_Lists.append(Items(china_sido=row['sido'],china_sigungu=row['sigungu'],china_cityGubun=row['cityGubun'],china_marketType=row['marketType']\
		, china_dtYearMonth=row['dtYearMonth'],  china_userCount=row['userCount'],  china_useCount=row['useCount'], china_useCost=row['useCost']))

		print(row['sido'], row['sigungu'], row['cityGubun'], row['marketType'],\
		row['dtYearMonth'], row['userCount'], row['useCount'], row['useCost'])

	Items.objects.using(db_alias).bulk_create(Item_Lists)


	print ("CHINA! DONE!")


	Items = apps.get_model("mainapp", "Korea_Item")

	ret = RD.getKoreanData("200001","201911",None,None,None,None,None,None,None)

	print (len(ret))

	Item_Lists = []
	for index, row in ret.iterrows():
		Item_Lists.append(Items(korea_sido=row['sido'],korea_sigungu=row['sigungu'],korea_cityGubun=row['cityGubun'],korea_marketType=row['marketType'], korea_userType=row['userType'], korea_ageGroup=row['ageGroup'], \
		korea_gender=row['gender'], korea_dtYearMonth=row['dtYearMonth'],  korea_userCount=row['userCount'],  korea_useCount=row['useCount'], korea_useCost=row['useCost']))

		print(row['sido'], row['sigungu'], row['cityGubun'], row['marketType'], row['userType'], row['ageGroup'], row['gender'], \
		row['dtYearMonth'], row['userCount'], row['useCount'], row['useCost'])

	Items.objects.using(db_alias).bulk_create(Item_Lists)

	print ("KOREA! DONE!")

class Migration(migrations.Migration):

	dependencies = [
		('mainapp', '0005_auto_20191122_1455'),
	]

	operations = [
		migrations.RunPython(forwards_func),
	]
